services:
  postgres:
    image: postgres:14.3
    container_name: myPostgresDB
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: adm321
      POSTGRES_DB: postgresDB
    ports:
      - "5455:5432"
    networks:
      - shared-network
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./data_extractor
      dockerfile: Dockerfile
    image: myapp:1.0
    container_name: my-extractor
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://adm:adm321@postgres:5432/postgresDB"
    networks:
      - shared-network

networks:
  shared-network:
    name: shared-network
    driver: bridge

volumes:
  pgdata: